Repository una-ada/Tabby, pull requests merged in 2021-07, with the labels that each got.

#2 fix(docs): update readme title
  README.md
Labels: docs

#4 fix: revert PR #3 merge
  Tabby/settings.py
  main_app/__init__.py
  main_app/admin.py
  main_app/apps.py
  main_app/migrations/__init__.py
  main_app/models.py
  main_app/tests.py
  main_app/views.py
Labels: lint

#5 about section, html, css
  Tabby/urls.py
  main_app/static/css/style.css
  main_app/templates/about.html
  main_app/templates/base.html
  main_app/urls.py
  main_app/views.py
Labels: feat

#30 fix(route): connect trips views
  main_app/urls.py
  main_app/views.py
Labels: fix

#31 refactor(view): rename views
  main_app/templates/trips/confirm_delete.html
  main_app/templates/trips/create.html
  main_app/views.py
Labels: refactor

#32 feat: add authentication
  Tabby/settings.py
  Tabby/urls.py
  main_app/templates/base.html
  main_app/templates/home.html
  main_app/templates/partials/header.html
  main_app/templates/registration/login.html
  main_app/templates/registration/signup.html
  main_app/templates/trips/confirm_delete.html
  main_app/templates/trips/create.html
  main_app/templates/trips/detail.html
  main_app/urls.py
  main_app/views.py
Labels: feat

#37 fix: re-add user to trip model
  main_app/migrations/0004_trip_user.py
  main_app/models.py
  main_app/views.py
Labels: fix

#39 fix: add auth to notes and diary entries
  main_app/migrations/0008_note_user.py
  main_app/models.py
  main_app/views.py
Labels: fix

#41 fix(ctrl): add authentication to diary entry CRUD
  main_app/templates/trips/detail.html
  main_app/views.py
Labels: fix

#44 feat: add note update and delete
  main_app/templates/main_app/note_confirm_delete.html
  main_app/templates/main_app/note_form.html
  main_app/templates/trips/confirm_delete.html
  main_app/templates/trips/detail.html
  main_app/templates/trips/trip_form.html
  main_app/urls.py
  main_app/views.py
Labels: feat

#54 infra: add deploy config
  Procfile
  Tabby/settings.py
  requirements.txt
Labels: infra

#63 fix: fix trip update
  main_app/templates/main_app/trip_form.html
  main_app/views.py
Labels: fix
